### ISSUE TITLE
random nits

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/multi-value#10]
Random list of nits as I was scanning https://webassembly.github.io/multi-value:
* In the binary encoding of blocktype, the prose says ", or as a type index encoded as a positive signed integer." but the formalism doesn't express the positive constraint on `x`.
* The validation notes for `block`, `loop` and `if` still say `t`<sup>`?`</sup>, not `t`<sup>`*`</sup>.
* The prose for `loop` validation say s "Let C′ be the same context as C, but with the *empty* result type [t1*] prepended to the labels vector.".

**Comment by rossberg** [comment]
All good catches, please see #11.

**Comment by lukewagner** [comment]
Thanks!
