### ISSUE TITLE
[js-api] Materialise multiple results as arrays

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/multi-value#12]
As [per last year's TPAC meeting](
https://github.com/WebAssembly/meetings/blob/master/2018/TPAC.md#multi-value-andreas-rossberg), we decided to allow multiple function results across the Wasm/JS boundary by materialising a JS array.

@littledan, assigning to you, since you volunteered to spec it

**Comment by littledan** [comment]
@rossberg What issues do you see with https://github.com/WebAssembly/multi-value/pull/8 ?

**Comment by rossberg** [comment]
Oops, sorry, I had completely forgotten about the open PR.
