### ISSUE TITLE
Please publish the jsapi spec

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/multi-value#19]
Publishing via travis seems to fail because it wants someone to enter a passphrase: https://travis-ci.com/WebAssembly/multi-value/builds/109870478

**Comment by kmiller68** [comment]
Yeah, that'd be great!

**Comment by rossberg** [comment]
Done, installed fresh deploy_key (after I figured out how to do that).

**Comment by rossberg** [comment]
@kmiller68, btw, I noticed this morning that Safari suddenly garbles the layout of the [landing page](https://webassembly.github.io/multi-value/index.html), not just here but also for the [main spec](https://webassembly.github.io/spec/index.html). Neither page changed, they render fine on Chrome, and used to do so on Safari, too. Any idea?

**Comment by kmiller68** [comment]
Hmm, it seems normal to me? Can you file a bug on bugs.webkit.org and CC me?

**Comment by Ms2ger** [comment]
Thank you! (Should we have documentation on what's necessary to set up a proposal repository somewhere?)

**Comment by rossberg** [comment]
@Ms2ger, ha, I was starting to write exactly that while I did the above! Wanted to create a PR once I had a chance to test it with a new proposal.

**Comment by rossberg** [comment]
@Ms2ger, see https://github.com/WebAssembly/proposals/pull/54
