### ISSUE TITLE
Clarification of "run a host function" algorithm

### ISSUE THREAD

**Issue by mstarzinger** [WebAssembly/multi-value#24]
This is about the "run a host function" algorithm described in section 3.6 of the WebAssembly JavaScript Interface for this proposal. Currently step 10.1 of the algorithm loads the `@@iterator` property from `result`, which is an internal vector taken from the function type. Since this is not a JavaScript object, I don't fully follow the expected semantics of this step. Is this maybe a typo and was supposed to load the `@@iterator` property from `ret` instead?

**Comment by littledan** [comment]
@Ms2ger Could you take a look into fixing this likely typo?
