### ISSUE TITLE
Differentiating void block type from type index

### ISSUE THREAD

**Issue by tlively** [WebAssembly/multi-value#28]
I think I must be missing something obvious, but how is the empty block type (0x40) supposed to be differentiated from type index 64 in the binary format?

**Comment by kmiller68** [comment]
Because the index form is decoded as a signed LEB, which sign extends the second most significant bit of the top byte. So 0x40 decodes to some negative number (I don’t recall which one exactly) and can’t intersect with a valid index.

**Comment by Hawk777** [comment]
Sorry to drag up an old question, but [it looks to me as if a `typeidx` is unsigned](https://webassembly.github.io/multi-value/core/binary/modules.html#indices). I think *I* must be missing something obvious, too?

To sanity check myself, I tried compiling a Rust module with 150 functions with different type signatures and looking at the `.wasm` file in a hex editor. The functions section contained a single-byte 0x40 type index.

**Comment by rossberg** [comment]
@Hawk777, a blocktype [encodes a type index as signed](https://webassembly.github.io/multi-value/core/binary/instructions.html#binary-blocktype).

**Comment by Hawk777** [comment]
Oh so it does. Thanks!
