### ISSUE TITLE
[question] why does functype validation is dropped from module/moduleinst?

### ISSUE THREAD

**Issue by Huxpro** [WebAssembly/multi-value#30]
Both [multi-value - valid-module](https://webassembly.github.io/multi-value/core/valid/modules.html#valid-module) and [multi-value - valid moduleinst](https://webassembly.github.io/multi-value/core/appendix/properties.html#module-instances) dropped the 

```
(⊢ functype ok)*
```

checks which was existing in [spec - valid-module](https://webassembly.github.io/spec/core/valid/modules.html#valid-module) and [spec - valid moduleinst](https://webassembly.github.io/spec/core/appendix/properties.html#module-instances)

I was curious about the reason behind it?

**Comment by rossberg** [comment]
Hm, interesting. I can't say offhand what the reason is, may be some merge gone bad. I'll investigate.
