### ISSUE TITLE
Fresh new link to rendered document

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/multi-value#5]
It looks like the link https://webassembly.github.io/multi-value/ in #1 no longer works.  Could you post another?  I was thinking that, since these links are most useful and sometimes hard to find in random issues, a convention could be to include the link in the root directory Readme.md (right below the link to the Overview.md)?

**Comment by rossberg** [comment]
Good idea, done. Also, marked the rendered doc as "Release 1.0 + multiple values" on its main page.

I did the same in the reference-types and teil-call repos.

**Comment by lukewagner** [comment]
Perfect, thanks!
